[build]
  command = "go build -o bin/main cmd/server/main.go"
  functions = "netlify/functions"
  publish = "bin"

[build.environment]
  GO_VERSION = "1.21"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/main/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "netlify/functions"
