[build]
builder = "nixpacks"

[deploy]
startCommand = "./bin/server"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[variables]
PORT = "8080"
GO_DEBUG = "false"
